---
id: pastie
name: Pastie
full: Pastebin application
description: >-
  An application for pasting and sharing syntax-highlighted snippets of
  arbitrary text or program code
list: ~
type: application
authors:
  -
    name: Ralf Lang
    user: lang
    email: lang@b1-systems.de
    active: true
    role: lead
  -
    name: Ben Klang
    user: bklang
    email: ~
    active: true
    role: lead
  -
    name: Jan Schneider
    user: jan
    email: jan@horde.org
    active: true
    role: lead
version:
  release: 1.0.0alpha2
  api: 1.0.0alpha1
state:
  release: alpha
  api: alpha
license:
  identifier: BSD-2-Clause
  uri: http://www.horde.org/licenses/bsd
dependencies:
  required:
    php: ^7
    composer:
      horde/horde: ^6
