<?php
/**
 * See horde/config/prefs.php for documentation on the structure of this file.
 *
 * IMPORTANT: DO NOT EDIT THIS FILE! DO NOT COPY prefs.php TO prefs.local.php!
 * Local overrides ONLY MUST be placed in var/config/pastie/prefs.local.php or
 * var/config/pastie/prefs.d/.
 * If the 'vhosts' setting has been enabled in Horde's configuration, you can
 * use var/config/pastie/prefs-servername.php.
 */

$prefGroups['Sample'] = array(
    'column' => _("Sample Prefs"),
    'label' => _("Sample Pref"),
    'desc' => _("Set your sample preference."),
    'members' => array('sample')
);

$_prefs['sample'] = array(
    'value' => '',
    'locked' => false,
    'type' => 'text',
    'desc' => _("This is your sample preference.")
);
